version: "3"
services:

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file: 
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=omshanti
      - DATABASE_NAME=social_media_fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=cc1ea1ef414964dcd35885a7f8296b8fc54d047ac1459455c4ea3a653ac5a570
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30


  
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: social_media_fastapi
      POSTGRES_PASSWORD: omshanti
    volumes:
      - postgres-db:/var/lib/postgresql/data
      
volumes:
  postgres-db:

    